source 'https://rubygems.org'

gem 'rails', '~> 5.1.3'
# Use mysql2 as the database for Active Record
gem 'mysql2', '~> 0.4.8'
# Paperclip as the image manager
# gem 'paperclip', '~> 5.1'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use jquery for convenience
gem 'jquery-rails'
# Use ReactJS as a replacement for the view in the MVC archetecture
gem 'react-rails'
# Useing material design icons!
gem 'material_icons', '~> 2.2', '>= 2.2.1'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Responders for responding in JSON
gem 'responders', '~> 2.1', '>= 2.1.1'

group :development do
  # Access an IRB console by using <%= console %> anywhere in the code.
  gem 'web-console', '~> 2.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
