# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8f14f1351562a3d737df99832e52fdb1f91628abdf283b2596b522c549d4f2b01c71164a7095b2332be8d536f30f5996c180c7709e75a7c0749b50c5e447f73

test:
  secret_key_base: d57a76b71ad37557868ee5289a657c41bf05cac0f91dfe5e2e6a4efe913ae0a573db8176a3dbf0c05d0c4faecd0bcd57aabbaff60365cefa12a80932fd1ae2d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
